chore: add Radon to tag `slashbots`
sapphiredev/sapphire-application-commands pull request #94
Opened 2022-03-27 16:37 UTC by EvolutionX-10

2022-03-27 20:46 UTC, favna requested changes

2022-03-27 20:46 UTC, favna commented on src/tags/tags.toml
> +- [**Radon** **2** **4**](https://github.com/EvolutionX-10/Radon)
```suggestion
- [**Radon** **3** **4**](https://github.com/EvolutionX-10/Radon)
```

- Your bot doesn't use ESM as it doesn't have `"type": "module"` in the package.json
- Due to the kinda hard to read code (lack of blank lines, easily readable formatted code, and some magic numbers here and there) I'd rather this be marked as advanced

2022-03-28 03:10 UTC, EvolutionX-10 commented on src/tags/tags.toml
> +- [**Radon** **2** **4**](https://github.com/EvolutionX-10/Radon)
Sure, will consider your suggestion!

2022-03-28 10:28 UTC, favna approved these changes

2022-03-28 10:28 UTC, merged